import "./globals.css";

import type { Metadata } from "next";
import { Gabarito } from "next/font/google";

const gabarito = Gabarito();

export const metadata: Metadata = {
  title: "Facebook",
  description: "Generated by Elias Alexandre",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR antialiased">
      <body className={gabarito.className}>{children}</body>
    </html>
  );
}
